### ISSUE TITLE
Compatibility broken with rust 1.41

### ISSUE THREAD

**Issue by jeroen** [rust-lang/backtrace-rs#412]
Not sure if this is considered important, otherwise feel free to close!

As of commit https://github.com/rust-lang/backtrace-rs/commit/c27d7c5af29cf99ba354812cf0cd8829851d91f9 this crate no longer compiles with the stock [rustc 1.41 on the latest Debian](https://packages.debian.org/buster/rustc) releases. The compilation fails when compiling `object-0.23.0`.

```
error[E0658]: subslice patterns are unstable
   --> /tmp/Rtmp90SLnd/R.INSTALL204d8c202e2/gifski/src/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:162:41
    |
162 |             [0x7f, b'E', b'L', b'F', 1, ..] => FileKind::Elf32,
    |                                         ^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62254

error[E0658]: subslice patterns are unstable
   --> /tmp/Rtmp90SLnd/R.INSTALL204d8c202e2/gifski/src/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:164:41
    |
164 |             [0x7f, b'E', b'L', b'F', 2, ..] => FileKind::Elf64,
    |                                         ^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62254

error[E0658]: subslice patterns are unstable
   --> /tmp/Rtmp90SLnd/R.INSTALL204d8c202e2/gifski/src/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:166:38
    |
166 |             [0xfe, 0xed, 0xfa, 0xce, ..]
    |                                      ^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62254
```

This had caught me a bit by surprise, and I had to do a hotfix release of my application to downgrade to `backtrace 0.3.55` in order for it to work on Debian.

**Comment by philipc** [comment]
I'm not a maintainer for this crate, but I think that's fine, I was just surprised because your other comment said 1.43.1. See https://github.com/rust-lang/backtrace-rs/issues/211#issuecomment-504970353 regarding minimum rust version for this crate.

**Comment by alexcrichton** [comment]
Thanks for the report, but this isn't considered a breaking change for this crate, so I'm going to close.
